// dict 字典名称
export const DICT_ADDRESS_TYPE = 'address_type' // 地址类型
export const DICT_CONTRACT_HANDLE_STATE = 'contract_handle_state' // 签约类型
export const DICT_CONTRACT_SIGN_TYPE = 'contract_sign_type' // 签约类型
export const DICT_CONTRACT_SIGN_MODE = 'contract_sign_mode' // 签订形式
export const DICT_ENTERPRISE_NATURE = 'enterprise_nature' // 企业性质
export const DICT_PIECES_UNIT_TYPE = 'pieces_unit_type' // 件数单位
export const DICT_UNIT = 'unit' // 单位
export const DICT_FEE_INQUIRY_STATUS = 'fee_inquiry_status' // 状态
export const DICT_FEE_PAY_TYPE = 'fee_pay_type' // 付汇类型
export const DICT_STORAGE_CYCLE = 'storage_cycle' // 结算方式
export const DICT_COMMON_SETTLEMENT = 'settlement' // 结算方式
export const DICT_DELIVERY_MODE = 'delivery_mode' // 送货方式
export const DICT_ADDED_SERVICES = 'added_services' // 增值服务类型
export const DICT_STAR_LEVEL = 'star_level' // 客户等级
export const DICT_CUSTOMER_STATUS = 'customer_status' // 客户状态
export const DICT_TRACK_TYPE = 'track_type' // 跟进类型
export const DICT_CUSTOMER_SOURCE = 'customer_source' // 客户来源
export const DICT_CUSTOMER_TYPE = 'customer_type' // 客户类型
export const DICT_EDA_TYPE = 'eda_type' // 询盘状态
export const DICT_CUSTOMER_LEVEL = 'customer_level' // 客户等级
export const DICT_INQUIRY_STATUS = 'inquiry_status' // 询盘状态
export const DICT_STORAGE_MODE = 'storage_mode' // 存储方式
export const DICT_STORAGE_BARN_AREA = 'storage_barn_area' //  用途仓区
export const DICT_PORT = 'open_port' // 口岸
export const DICT_TRADE_PAY_METHOD = 'trade_pay_method' // 贸易方式
export const DICT_PACKAGING_METHOD = 'packaging_method' // 包装方式
export const DICT_INVOICING_MODE = 'invoicing_mode' // 开发票要求
export const DICT_RELEASE_MODE = 'release_mode' // 放货方式
export const DICT_PFE_TYPE = 'pfe_type' // 付汇类型
export const DICT_PFE_STATUS = 'pfe_status' // 付汇状态
export const DICT_HANDING_FEE_PAYMENT = 'pfe_handing_fee_payment' // 手续费承担情况
export const DICT_OCM_ORDER_STATUS = 'order_status' // 订单状态
export const DICT_ORDER_MARINE_STATUS = 'order_marine_status' // 海运状态
export const DICT_ORDER_BOOKING_STATUS = 'order_booking_status' // 订舱状态
export const DICT_ORDER_AIRLIFT_STATUS = 'order_airlift_status' // 空运状态
export const DICT_ORDER_CCL_STATUS = 'order_ccl_status' // 报关跟踪状态
export const DICT_SERVICE_CODE = 'ck_service_code' // 服务类型
export const DICT_ORDER_FEE_TYPE = 'order_fee_type' // 订单费用类型
export const DICT_ASSIGN_STATUS = 'assign_status' // 订单分派状态
export const DICT_ORDER_STATUS = 'order_status' // 订单状态
export const DICT_YSE_OR_NO = 'sys_yes_no'
export const DICT_CHECK_TYPE = 'check_type' // 查验类型
export const DICT_CHECK_METHOD = 'check_method' // 检验类型
export const DICT_TRADE_TERMS = 'trade_terms' // 贸易条款
export const DICT_CABINET_TYPE = 'cabinet_type' // 柜型
export const DICT_TAX_PAYMENT_METHOD = 'tax_payment_method' // 缴税方式
export const DICT_COOPERATE_TYPE = 'cooperate_type' // 合作类型
export const DICT_NOTICE_RECIEPT_STATUS = 'notice_reciept_status' // 入库通知书状态
export const DICT_ORDER_NOTICE_RECIEPT_STATUS = 'order_notice_reciept_status' // 入库通知书状态
export const DICT_NOTICE_OUTBOUND_STATUS = 'notice_outbound_status' // 出库通知书状态
export const DICT_ORDER_NOTICE_OUTBOUND_STATUS = 'order_notice_outbound_status' // 出库通知书状态
export const DICT_WAREHOUSE_TYPE = 'warehouse_type' // 仓库类型
export const DICT_QUOTATION_STATUS = 'quotation_status' // 报价单状态
export const DICT_DELIVER_NOTICE_STATUS = 'deliver_notice_status' // 拖车通知书状态
export const DICT_CHARGE_TYPE = 'charge_type' // 计费类型
export const DICT_OPERATE_TYPE = 'operate_type' // 计费类型
export const DICT_FEE_TYPE = 'fee_type' // 计费类型
export const DICT_FEE_BILL_TYPE = 'fee_bill_type' //费用账单类型
export const DICT_LICENSE_STATUS = 'license_status' //费用账单类型

/** 报价单费用状态 */
export const DICT_QUOTATION_FEE_STATUS = 'quotation_fee_status'
export const DICT_REVIEW_STATUS = 'review_status' // 审核状态
export const DICT_ORDER_FEE_STATUS = 'order_fee_status' // 订单费用状态
export const DICT_FILE_TYPE_ORDER = 'file_type_order' // 附件类型 - 订单
export const DICT_FILE_TYPE_CUSTOMER = 'file_type_customer' // 附件类型 - 客户
export const DICT_FILE_TYPE_OTHER = 'file_type_other' // 附件类型 - 其他
export const DICT_FEE_FORMED_BILL_STATUS = 'fee_formed_bill_status' // 应收票据状态
export const DICT_BILL_STATUS = 'bill_status' // 应收账单状态
export const DICT_GOODS_STATUS = 'goods_status' // 货物状态
export const DICT_OPEN_PORT = 'open_port' // 适用口岸
export const DICT_RISK_LEVEL = 'risk_level' // 适用口岸
export const DICT_CONSIGNMENT_TYPE = 'consignment_type' // 托运类型
export const DICT_SUPPLIER_LIST = 'supplier_list' // 公司列表
export const DICT_CUSTOMER_CONTRACT_NAME = 'customer_contract_name' // 客户合同
export const DICT_INSURE_TYPE = 'insure_type' // 保险类型
export const DICT_ORDER_INSURER_STATUS = 'order_insure_status' // 保险类型
export const DICT_TRANSPORT_MODE = 'transport_mode' // 运输方式
export const DICT_CONFIG_TYPE = 'user_config_type' // 用户配置
export const DICT_USER_CONFIG_V_PAGE_SIZE = 'user_config_v_page_size' // 列表查询分页大小
export const DICT_CHARGED_WEIGHT_TYPE = 'charged_weight_type' // 计费重量
export const DICT_CALENDAR_REMIND_REPEAT_TYPE = 'calendar_remind_repeat_type' // 日程提醒重复类型
export const DICT_CALENDAR_REMIND_BEFORE_SECS = 'calendar_remind_before_secs' // 日程提醒提前时间
export const DICT_BILL_PAYMENT_TYPE = 'bill_payment_type' // 账单收付类型
export const DICT_TRANSFER_METHOD = 'transfer_method' // 转账方式
export const DICT_CCL_TYPE = 'ck_ccl_type' // 报关类型
export const DICT_SEND_RECEIVE_TYPE = 'send_receive_type' // 收取类型
export const DICT_CUSTOMER_ASSIGN_TYPE = 'customer_assign_type' // 分派类型
export const DICT_FUNDS_APPLY_SUPPLIER_STATUS = 'funds_apply_supplier_status' // 供应商请款状态
export const DICT_FUNDS_APPLY_REPLACEMENT_STATUS = 'funds_apply_supplier_status' // 换单请款状态
export const DICT_FUNDS_APPLY_PROXY_TAX_STATUS = 'funds_apply_proxy_tax_status' // 代垫税款请款状态
export const DICT_FUNDS_APPLY_P2GR_STATUS = 'funds_apply_p2gr_status' // 供应商请款状态
export const DICT_FUNDS_APPLY_CUSTOMER_STATUS = 'funds_apply_customer_status' // 对账单状态
export const DICT_CUSTOMER_RECONCILIATION_VERIFY_METHOD = 'customer_reconciliation_verify_method' // 核销方式
export const DICT_CCL_TRACE_STATUS = 'ccl_trace_status' // 核销方式
export const DICT_ORDER_SERVE_PLATE = 'order_serve_plate' // 订单服务概览板块